// This file is auto-generated by generate-wire-mappings.ts. Do not edit.

/**
 * One field-rename rule produced from a `@wire` JSDoc tag in the contracts.
 * The SDK applies the rename at the HTTP boundary — outbound when the runtime
 * value of `tsName` is in `triggerValues` (or unconditionally if it is `null`),
 * inbound whenever the response carries `wireName`.
 */
export interface WireFieldMapping {
  readonly tsName: string;
  readonly wireName: string;
  /** When non-null, only rename if the value is in this set. */
  readonly triggerValues: readonly string[] | null;
}

export const WIRE_FIELD_MAPPINGS: readonly WireFieldMapping[] = [
  {
    tsName: 'type',
    wireName: '$type',
    triggerValues: ['audio', 'display', 'exact', 'exceeding', 'other', 'range'],
  },
];
